"""Built-in demo asset generation for Visible Layers."""

from __future__ import annotations

import shutil
from pathlib import Path

from PIL import Image, ImageDraw

from .gaps import detect_gaps
from .layers import split_layers
from .preview import save_preview


def create_demo(output_dir: str | Path, *, overwrite: bool = False) -> dict[str, str]:
    root = Path(output_dir)
    if root.exists() and any(root.iterdir()):
        if not overwrite:
            raise FileExistsError(f"Demo output already exists and is not empty: {root}")
        shutil.rmtree(root)

    root.mkdir(parents=True, exist_ok=True)
    masks_dir = root / "masks"
    asset_output_dir = root / "output"
    gaps_dir = asset_output_dir / "gaps"
    masks_dir.mkdir()

    input_path = root / "input.png"
    source = make_demo_input()
    source.save(input_path)

    for name, mask in make_demo_masks().items():
        mask.save(masks_dir / f"{name}.png")

    metadata = split_layers(input_path, masks_dir, asset_output_dir)
    preview_path = asset_output_dir / "preview.png"
    save_preview(asset_output_dir / "character.json", preview_path)
    gap_report = detect_gaps(asset_output_dir / "character.json", gaps_dir)
    write_demo_readme(root)

    return {
        "root": str(root),
        "input": str(input_path),
        "masks": str(masks_dir),
        "metadata": str(asset_output_dir / "character.json"),
        "layers": str(asset_output_dir / "layers"),
        "preview": str(preview_path),
        "gaps": str(gaps_dir),
        "gap_report": str(gap_report["report"]),
        "layer_count": str(len(metadata["layers"])),
    }


def make_demo_input(size: tuple[int, int] = (256, 256)) -> Image.Image:
    image = Image.new("RGBA", size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)

    draw.rectangle((56, 50, 200, 218), fill=(118, 220, 156, 255))
    draw.rectangle((70, 92, 186, 210), fill=(245, 247, 239, 255))
    draw.rectangle((86, 52, 170, 118), fill=(255, 217, 187, 255))
    draw.rectangle((76, 42, 180, 78), fill=(74, 156, 91, 255))
    draw.polygon([(76, 78), (96, 78), (88, 100)], fill=(74, 156, 91, 255))
    draw.polygon([(126, 78), (146, 78), (136, 104)], fill=(74, 156, 91, 255))
    draw.rectangle((48, 104, 76, 190), fill=(255, 217, 187, 255))
    draw.rectangle((180, 104, 208, 190), fill=(255, 217, 187, 255))
    draw.rectangle((42, 154, 54, 226), fill=(255, 108, 178, 255))
    draw.rectangle((202, 154, 214, 226), fill=(255, 108, 178, 255))

    draw.rectangle((101, 80, 113, 92), fill=(34, 40, 49, 255))
    draw.rectangle((143, 80, 155, 92), fill=(34, 40, 49, 255))
    draw.rectangle((118, 102, 138, 108), fill=(34, 40, 49, 255))

    # A deliberate missing square in the body mask will make gap detection visible.
    draw.rectangle((120, 150, 136, 166), fill=(245, 247, 239, 255))
    return image


def make_demo_masks(size: tuple[int, int] = (256, 256)) -> dict[str, Image.Image]:
    masks: dict[str, Image.Image] = {}

    masks["00_body_base"] = mask_with_rectangles(
        size,
        [(56, 50, 200, 218)],
        holes=[(120, 150, 136, 166)],
    )
    masks["10_face_base"] = mask_with_rectangles(size, [(86, 52, 170, 118)])
    masks["20_front_hair"] = mask_with_polygon(
        size,
        [
            [(76, 42), (180, 42), (180, 78), (146, 78), (136, 104), (126, 78), (96, 78), (88, 100), (76, 78)],
        ],
    )
    masks["30_left_arm"] = mask_with_rectangles(size, [(48, 104, 76, 190), (42, 154, 54, 226)])
    masks["40_right_arm"] = mask_with_rectangles(size, [(180, 104, 208, 190), (202, 154, 214, 226)])

    return masks


def mask_with_rectangles(
    size: tuple[int, int],
    rectangles: list[tuple[int, int, int, int]],
    *,
    holes: list[tuple[int, int, int, int]] | None = None,
) -> Image.Image:
    mask = Image.new("L", size, 0)
    draw = ImageDraw.Draw(mask)
    for rectangle in rectangles:
        draw.rectangle(rectangle, fill=255)
    for hole in holes or []:
        draw.rectangle(hole, fill=0)
    return mask


def mask_with_polygon(size: tuple[int, int], polygons: list[list[tuple[int, int]]]) -> Image.Image:
    mask = Image.new("L", size, 0)
    draw = ImageDraw.Draw(mask)
    for polygon in polygons:
        draw.polygon(polygon, fill=255)
    return mask


def write_demo_readme(root: Path) -> None:
    text = "\n".join(
        [
            "# Visible Layers Demo Output",
            "",
            "This folder was generated by `visible-layers demo`.",
            "",
            "- `input.png` is a synthetic flat character image.",
            "- `masks/` contains grayscale masks for the first layer extraction step.",
            "- `output/layers/` contains transparent PNG layers.",
            "- `output/preview.png` is the recomposed layer stack.",
            "- `output/gaps/` contains a simple transparent-gap mask and report.",
            "",
            "The demo intentionally includes a small missing region in the body mask so gap detection has something visible to report.",
            "",
        ]
    )
    (root / "README.md").write_text(text, encoding="utf-8")
